/*
 * Copyright 2015 Palantir Technologies, Inc. All rights reserved.
 */

buildscript {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }

    dependencies {
        classpath 'com.palantir.baseline-error-prone:gradle-baseline-error-prone:0.26.0'
        classpath 'com.palantir.jakartapackagealignment:jakarta-package-alignment:0.7.0'
        classpath 'com.palantir.gradle.jdks:gradle-jdks:0.82.0'
        classpath 'com.palantir.gradle.jdkslatest:gradle-jdks-latest:0.32.0'
        classpath 'com.palantir.gradle.externalpublish:gradle-external-publish-plugin:2.0.0'
        classpath 'com.palantir.gradle.failure-reports:gradle-failure-reports:1.21.0'
        classpath 'com.palantir.javaformat:gradle-palantir-java-format:2.97.0'
        classpath 'com.palantir.suppressible-error-prone:gradle-suppressible-error-prone:2.33.0'
        classpath 'com.palantir.gradle.consistentversions:gradle-consistent-versions:3.19.0'
        classpath 'com.palantir.baseline:gradle-baseline-java:7.9.0'
        classpath 'com.palantir.gradle.gitversion:gradle-git-version:5.1.0'
        classpath 'com.palantir.gradle.idea-configuration:gradle-idea-configuration:0.11.0'
        classpath 'me.champeau.jmh:jmh-gradle-plugin:0.7.3'
    }
}

apply plugin: 'com.palantir.external-publish'
apply plugin: 'com.palantir.failure-reports'
apply plugin: 'com.palantir.baseline'
apply plugin: 'com.palantir.baseline-error-prone-root'
apply plugin: 'com.palantir.git-version'
apply plugin: 'com.palantir.jdks'
apply plugin: 'com.palantir.consistent-versions'
apply plugin: 'com.palantir.baseline-java-versions'
apply plugin: 'com.palantir.jdks.latest'

javaVersions {
    javaCompiler = 25
    libraryTarget = 17
    runtime = 25
}

allprojects {
    apply plugin: 'com.palantir.java-format'
    apply plugin: 'com.palantir.jakarta-package-alignment'
    repositories {
        mavenCentral() { metadataSources { mavenPom(); ignoreGradleMetadataRedirection() } }
    }

    group 'com.palantir.common'
    version System.env.CIRCLE_TAG ?: gitVersion()
}

subprojects {
    apply plugin: 'java-library'
    apply plugin: 'com.palantir.java-format'

    tasks.check.dependsOn(javadoc)
    tasks.check.dependsOn(checkImplicitDependencies)
    tasks.check.dependsOn(checkUnusedDependencies)
    tasks.check.dependsOn(checkUnusedConstraints)
}

jdks {
    daemonTarget = 21
}
